version: '3.9'
services:
  mysql:
    restart: always
    image: mysql:8.0.29
    container_name: mysql-app
    ports:
      - "3307:3307"
    volumes:
      - /home/eduardo/arquivosdocker/.docker/db:/var/lib/mysql
    networks:
      - redegrupo5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql_app

  mysql-admin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: mysql-phpmyadmin
    ports:
      - "8001:80"
    networks:
      - redegrupo5
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_USER: root
      PMA_PASSWORD: root

  redis-server:
    restart: always
    image: redis
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data
    networks:
      - redegrupo5

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  redegrupo5:
    driver: bridge
